### ISSUE TITLE
Revert Controller and Commands Refactor to Avoid Static Lists

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/sistema-de-gestion-deportiva#19] opened 2024-12-06 02:36 UTC
# Revert Controller and Commands Refactor to Avoid Static Lists

## Description:

This reverts the changes made in PR #14, which introduced a refactor of the controller and commands. The main reason for this revert is to address the usage of static lists, which is not recommended due to potential issues with scalability, testability, and thread safety.

## Reason for Revert:

**Avoiding Static Lists**: The new implementation relies on static lists, which can lead to unintended side effects across different parts of the system, making it difficult to maintain and test.

**Comment by javierdesant** [comment] 2024-12-06 02:38
Esto sería lo último, a ver si podemos volver al Controller original sin perder los cambios que ya hemos hecho.

**Comment by javierdesant** [comment] 2024-12-06 02:38
También quedaría enviarlo.
Por favor enviarlo en el plazo, que yo no estoy.

**Comment by gmottajr** [comment] 2024-12-06 03:45
Hi @javierdesant, @JhonyRetro, and @Cafileiro! 
I'd like to help with this issue if additional hands are needed. Let me know if I can contribute in any way. Thanks!

**Comment by JhonyRetro** [comment] 2024-12-06 03:47
I think I can avoid using static lists creating a ServiceCoordinator class, I'm looking into it.

**Comment by JhonyRetro** [comment] 2024-12-06 04:06
Managed to remove static list usage using this new class. Will be closing this issue since the problem is now solved.
Check e5a52761abb7d3343b2f3bd68a3a24986565d1f7 and ff275554541d7c3f41b4d88aa5eaacdeb21499a5

**Closed by JhonyRetro** 2024-12-06 04:06 UTC
Labels: bug, enhancement, help wanted
